# version format
version: 1.0.{build}

branches:
  except:
    - gh-pages

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

cache:
  - packages -> **\packages.config

install:
  - choco install docfx

build_script:
  - docfx metadata
  - docfx build

test: off

